id: ACDDE2C23
title: 'Music to Delight the Ḍākinī: A Praise to the Deathless Mandāravā'
type: translation
pechas:
- IE1B001A2
- IEFB049DE
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:35:11.710192
  last_modified_at: 2023-01-04 12:35:11.710197
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IE1B001A2/1104: D7E8
  IEFB049DE/E098: D7E8
